Repository devfile/api, pull requests merged in 2021-01, with the labels that each got.

#280 Update Devfile API Go module to add version to module path
  generator/overrides/gen.go
  go.mod
  pkg/apis/addtoscheme_workspaces_v1alpha2.go
  pkg/apis/workspaces/v1alpha1/attributes_conversion.go
  pkg/apis/workspaces/v1alpha1/commands_conversion.go
  pkg/apis/workspaces/v1alpha1/commands_conversion_test.go
  pkg/apis/workspaces/v1alpha1/components_conversion.go
  pkg/apis/workspaces/v1alpha1/components_conversion_test.go
  pkg/apis/workspaces/v1alpha1/conversion.go
  pkg/apis/workspaces/v1alpha1/conversion_test.go
  pkg/apis/workspaces/v1alpha1/devworkspace_conversion.go
  pkg/apis/workspaces/v1alpha1/devworkspacetemplate_conversion.go
  pkg/apis/workspaces/v1alpha1/events_conversion.go
  pkg/apis/workspaces/v1alpha1/events_conversion_test.go
  pkg/apis/workspaces/v1alpha1/parent_conversion.go
  pkg/apis/workspaces/v1alpha1/parent_conversion_test.go
  pkg/apis/workspaces/v1alpha1/plugin_conversion.go
  pkg/apis/workspaces/v1alpha1/projects_conversion.go
  pkg/apis/workspaces/v1alpha1/projects_conversion_test.go
  pkg/apis/workspaces/v1alpha2/commands.go
  pkg/apis/workspaces/v1alpha2/components.go
  pkg/apis/workspaces/v1alpha2/devfile.go
  pkg/apis/workspaces/v1alpha2/endpoint.go
  pkg/apis/workspaces/v1alpha2/projects.go
  pkg/apis/workspaces/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go
  pkg/apis/workspaces/v1alpha2/zz_generated.plugin_overrides.go
  pkg/devfile/header.go
  pkg/devfile/header_test.go
  pkg/utils/overriding/keys.go
  pkg/utils/overriding/merging.go
  pkg/utils/overriding/overriding.go
  pkg/utils/overriding/overriding_test.go
  pkg/utils/unions/normalize.go
  pkg/utils/unions/normalize_test.go
Labels: lgtm

#285 Add tools for releasing the Devfile schema
  .github/workflows/release-schema.yaml
  docs/proposals/versioning-and-release.md
  make-release.sh
Labels: lgtm

#282 Index server REST APIs docs
  docs/proposals/registry/index-server-REST-API.md
Labels: area/documentation, lgtm

#289 change endpoint name limit to 63 characters
  crds/workspace.devfile.io_devworkspaces.v1beta1.yaml
  crds/workspace.devfile.io_devworkspaces.yaml
  crds/workspace.devfile.io_devworkspacetemplates.v1beta1.yaml
  crds/workspace.devfile.io_devworkspacetemplates.yaml
  pkg/apis/workspaces/v1alpha2/endpoint.go
  pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go
  pkg/apis/workspaces/v1alpha2/zz_generated.plugin_overrides.go
  pkg/validation/validation-rule.md
  schemas/latest/dev-workspace-template-spec.json
  schemas/latest/dev-workspace-template.json
  schemas/latest/dev-workspace.json
  schemas/latest/devfile.json
  schemas/latest/ide-targeted/dev-workspace-template-spec.json
  schemas/latest/ide-targeted/dev-workspace-template.json
  schemas/latest/ide-targeted/dev-workspace.json
  schemas/latest/ide-targeted/devfile.json
  schemas/latest/ide-targeted/parent-overrides.json
  schemas/latest/ide-targeted/plugin-overrides.json
  schemas/latest/parent-overrides.json
  schemas/latest/plugin-overrides.json
Labels: lgtm

#307 Update endpoint tests
  test/v200/devfiles/components/containerEndpointLongName.yaml
  test/v200/devfiles/components/kubernetesEndpointLongName.yaml
  test/v200/devfiles/components/openshiftEndpointLongName.yaml
  test/v200/json/component-parent-tests.json
  test/v200/json/component-tests.json
Labels: lgtm

#304 Release version 2.0.0
  pkg/apis/workspaces/v1alpha2/doc.go
  schemas/latest/dev-workspace-template-spec.json
  schemas/latest/dev-workspace-template.json
  schemas/latest/dev-workspace.json
  schemas/latest/devfile.json
  schemas/latest/ide-targeted/dev-workspace-template-spec.json
  schemas/latest/ide-targeted/dev-workspace-template.json
  schemas/latest/ide-targeted/dev-workspace.json
  schemas/latest/ide-targeted/devfile.json
  schemas/latest/ide-targeted/parent-overrides.json
  schemas/latest/ide-targeted/plugin-overrides.json
  schemas/latest/jsonSchemaVersion.txt
  schemas/latest/parent-overrides.json
  schemas/latest/plugin-overrides.json
Labels: lgtm

#305 Bump schema version on master to 2.1.0-alpha
  pkg/apis/workspaces/v1alpha2/doc.go
  schemas/latest/dev-workspace-template-spec.json
  schemas/latest/dev-workspace-template.json
  schemas/latest/dev-workspace.json
  schemas/latest/devfile.json
  schemas/latest/ide-targeted/dev-workspace-template-spec.json
  schemas/latest/ide-targeted/dev-workspace-template.json
  schemas/latest/ide-targeted/dev-workspace.json
  schemas/latest/ide-targeted/devfile.json
  schemas/latest/ide-targeted/parent-overrides.json
  schemas/latest/ide-targeted/plugin-overrides.json
  schemas/latest/jsonSchemaVersion.txt
  schemas/latest/parent-overrides.json
  schemas/latest/plugin-overrides.json
Labels: lgtm

#293 Add error DevWorkspace Phase and ConditionType
  pkg/apis/workspaces/v1alpha1/devworkspace_types.go
  pkg/apis/workspaces/v1alpha2/devworkspace_types.go
Labels: area/devworkspace, lgtm

#318 add more resources settings for container component
  crds/workspace.devfile.io_devworkspaces.v1beta1.yaml
  crds/workspace.devfile.io_devworkspaces.yaml
  crds/workspace.devfile.io_devworkspacetemplates.v1beta1.yaml
  crds/workspace.devfile.io_devworkspacetemplates.yaml
  pkg/apis/workspaces/v1alpha2/containerComponent.go
  pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go
  pkg/apis/workspaces/v1alpha2/zz_generated.plugin_overrides.go
  schemas/latest/dev-workspace-template-spec.json
  schemas/latest/dev-workspace-template.json
  schemas/latest/dev-workspace.json
  schemas/latest/devfile.json
  schemas/latest/ide-targeted/dev-workspace-template-spec.json
  schemas/latest/ide-targeted/dev-workspace-template.json
  schemas/latest/ide-targeted/dev-workspace.json
  schemas/latest/ide-targeted/devfile.json
  schemas/latest/ide-targeted/parent-overrides.json
  schemas/latest/ide-targeted/plugin-overrides.json
  schemas/latest/parent-overrides.json
  schemas/latest/plugin-overrides.json
Labels: lgtm
